trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'
  
variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)\.m2\repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

steps:
  - checkout: self
    clean: 'true'
    fetchDepth: '1'

  - task: Cache@2
    inputs:
      key: 'maven | "$(Agent.OS)"'
      path: $(MAVEN_CACHE_FOLDER)
    displayName: 'Cache Maven local repo'

  - script: |
      apt install openjdk-15
      mvn clean package --no-transfer-progress $(MAVEN_OPTS)
    displayName: 'Build deb package'
